import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Root from "@/components/RootLayout";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "RideRescue",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Root>{children}</Root>
      </body>
    </html>
  );
}
